name: Build and test images - Pull Request
on:
  pull_request:
    paths:
      - '**'

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
jobs:
  core:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
      family: archlinux
      base_image: archlinux:base
      model: generic
      variant: core
      arch: amd64
  install:
    uses: ./.github/workflows/reusable-install-test.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
    needs:
      - core
  acceptance:
    uses: ./.github/workflows/reusable-qemu-acceptance-test.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
    needs:
      - core

  bundles:
    uses: ./.github/workflows/reusable-qemu-bundles-test.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
    needs:
      - core

  reset:
    uses: ./.github/workflows/reusable-qemu-reset-test.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
    needs:
      - core
  netboot:
    uses: ./.github/workflows/reusable-qemu-netboot-test.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
      family: archlinux
      base_image: archlinux:24.04
      model: generic
      variant: core
    needs:
      - core
  upgrade:
    uses: ./.github/workflows/reusable-upgrade-with-cli-test.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
    needs:
      - core

  custom-partitioning:
    uses: ./.github/workflows/reusable-custom-partitioning-test.yaml
    with:
      flavor: ${{ matrix.flavor }}
      flavor_release: ${{ matrix.flavorRelease }}
    needs:
      - core
    strategy:
      fail-fast: true
      matrix:
        flavor:
          - "archlinux"
        flavorRelease:
          - "base"
  encryption:
    uses: ./.github/workflows/reusable-encryption-test.yaml
    with:
      flavor: archlinux
      flavor_release: "base"
      label: ${{ matrix.label }}
    needs:
      - core
    strategy:
      fail-fast: true
      matrix:
        label:
          - "local-encryption"
          - "remote-auto"
          - "remote-static"
          - "remote-https-pinned"
          - "remote-https-bad-cert"