name: Build and test images
on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '**'

permissions: read-all
concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
jobs:
  various:
    uses: ./.github/workflows/reusable-provider-tests.yaml
    permissions:
      contents: write
      security-events: write
      id-token: write
      actions: read
      attestations: read
      checks: read
      deployments: read
      discussions: read
      issues: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read
    with:
      flavor: ${{ matrix.flavor }}
      flavor_release: ${{ matrix.flavorRelease }}
      label: ${{ matrix.label }}

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - flavor: "opensuse"
            flavorRelease: "leap-15.6"
            label: "provider-decentralized-k8s"