name: Build and test PRs
on:
  pull_request:
    paths:
      - '**'

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
jobs:
  get-framework-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch --prune --unshallow
    - id: set-matrix
          # echo "matrix={\"include\": $content }" >> $GITHUB_OUTPUT
      run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            cat .github/flavors.json
            echo EOF
          } >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
  framework:
    uses: ./.github/workflows/reusable-build-framework-flavor.yaml
    secrets: inherit
    with:
      flavor: ${{ matrix.flavor }}
    needs:
      - get-framework-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.get-framework-matrix.outputs.matrix)}}
