name: Reusable workflow - image and iso arm generic build

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string
      flavor_release:
        required: true
        type: string
      family:
        required: true
        type: string
      base_image:
        required: true
        type: string
      variant:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      - name: Install earthly
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: Luet-lab/luet-install-action@v1.1
        with:
          repository: quay.io/kairos/packages
          packages: utils/earthly
      - name: Set up QEMU
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay Registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
      - name: Block all traffic to metadata ip  # For cloud runners, the metadata ip can interact with our test machines
        run: |
          sudo iptables -I INPUT -s 169.254.169.254 -j DROP
          sudo iptables -I OUTPUT -d 169.254.169.254 -j DROP
      - name: Build iso  🔧
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          earthly -P +all-arm-generic \
            --FAMILY=${{ inputs.family }} \
            --FLAVOR=${{ inputs.flavor }} \
            --FLAVOR_RELEASE=${{ inputs.flavor_release }} \
            --VARIANT=${{ inputs.variant }} \
            --BASE_IMAGE=${{ inputs.base_image }}

      - name: Push to quay
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          export IMAGE=$(cat build/IMAGE)
          docker push "$IMAGE"
      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          name: kairos-${{ inputs.flavor }}-${{ inputs.flavor_release }}-arm64.iso.zip
          path: |
            build/*.iso
            build/*.sha256
