name: UKI tests
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ci-uki-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
jobs:
  test-uki:
    strategy:
      matrix:
        include:
          - flavor: archlinux
            family: archlinux
            flavor_release: base
            base_image: archlinux:base
    uses: ./.github/workflows/reusable-uki-test.yaml
    secrets: inherit
    with:
      base_image: ${{ matrix.base_image }}
      family: ${{ matrix.family }}
      flavor: ${{ matrix.flavor }}
      flavor_release: ${{ matrix.flavor_release }}
